// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NebuloHub.Infraestructure.Context;

#nullable disable

namespace NebuloHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123175537_AjusteAvaliacaoStartup")]
    partial class AjusteAvaliacaoStartup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NebuloHub.Domain.Entity.Avaliacao", b =>
                {
                    b.Property<long>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_AVALIACAO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAvaliacao"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMENTARIO");

                    b.Property<long>("Nota")
                        .HasColumnType("bigint")
                        .HasColumnName("NOTA");

                    b.Property<string>("StartupCNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("STARTUP_CNPJ");

                    b.Property<string>("UsuarioCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CPF");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("StartupCNPJ");

                    b.HasIndex("UsuarioCPF");

                    b.ToTable("AVALIACAO", (string)null);
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Habilidade", b =>
                {
                    b.Property<long>("IdHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_HABILIDADE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdHabilidade"));

                    b.Property<string>("NomeHabilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_HABILIDADE");

                    b.Property<string>("TipoHabilidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_HABILIDADE");

                    b.HasKey("IdHabilidade");

                    b.ToTable("HABILIDADE", (string)null);
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Possui", b =>
                {
                    b.Property<long>("IdPossui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_POSSUI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPossui"));

                    b.Property<long>("IdHabilidade")
                        .HasColumnType("bigint")
                        .HasColumnName("ID_HABILIDADE");

                    b.Property<string>("StartupCNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CNPJ");

                    b.HasKey("IdPossui");

                    b.HasIndex("IdHabilidade");

                    b.HasIndex("StartupCNPJ");

                    b.ToTable("POSSUI", (string)null);
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Startup", b =>
                {
                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("EmailStartup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL_STARTUP");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_RESPONSAVEL");

                    b.Property<string>("NomeStartup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_STARTUP");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SITE");

                    b.Property<string>("UsuarioCPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CPF");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIDEO");

                    b.HasKey("CNPJ");

                    b.HasIndex("UsuarioCPF");

                    b.ToTable("STARTUP", (string)null);
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Usuario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SENHA");

                    b.Property<long?>("Telefone")
                        .HasColumnType("bigint")
                        .HasColumnName("TELEFONE");

                    b.HasKey("CPF");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Avaliacao", b =>
                {
                    b.HasOne("NebuloHub.Domain.Entity.Startup", "Startup")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("StartupCNPJ")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NebuloHub.Domain.Entity.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioCPF")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Startup");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Possui", b =>
                {
                    b.HasOne("NebuloHub.Domain.Entity.Habilidade", "Habilidade")
                        .WithMany("Possuis")
                        .HasForeignKey("IdHabilidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("ID_HABILIDADE_POSSUI_FK");

                    b.HasOne("NebuloHub.Domain.Entity.Startup", "Startup")
                        .WithMany("Possuis")
                        .HasForeignKey("StartupCNPJ")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("CNPJ_POSSUI_FK");

                    b.Navigation("Habilidade");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Startup", b =>
                {
                    b.HasOne("NebuloHub.Domain.Entity.Usuario", "Usuario")
                        .WithMany("Startups")
                        .HasForeignKey("UsuarioCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Habilidade", b =>
                {
                    b.Navigation("Possuis");
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Startup", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Possuis");
                });

            modelBuilder.Entity("NebuloHub.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Startups");
                });
#pragma warning restore 612, 618
        }
    }
}
